/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package irdc.ex05_21;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int blue=0x7f020003;
        public static final int darkgray=0x7f020001;
        public static final int icon=0x7f020000;
        public static final int white=0x7f020002;
    }
    public static final class id {
        public static final int myButton1=0x7f050002;
        public static final int myListView1=0x7f050001;
        public static final int myListViewLayout1=0x7f050003;
        public static final int myTextView1=0x7f050000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int simple_list_item_1=0x7f030001;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
        public static final int str_button1=0x7f040002;
        public static final int str_err_no_running_service=0x7f040005;
        public static final int str_err_no_running_task=0x7f040004;
        public static final int str_err_permission=0x7f040003;
    }
}
