/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.iceskysl.TestServiceHolder;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int face_1=0x7f020000;
        public static final int icon=0x7f020001;
    }
    public static final class id {
        public static final int bind_service=0x7f050002;
        public static final int start_service=0x7f050000;
        public static final int stop_service=0x7f050001;
        public static final int unbind_service=0x7f050003;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
        public static final int service_started=0x7f040002;
    }
}
