//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by T3DSystem.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_DIALOG_DEMSEPERATE          102
#define IDD_DIALOG_LOADTEXTURE          103
#define IDD_DIALOG_NEWPROJECT           104
#define IDD_DIALOG_OPENPROJECT          105
#define IDD_DIALOG_SPACESELECTSET       106
#define IDD_DIALOG_SCHEME               107
#define IDD_DIALOG_PLANE_R_l0           108
#define IDD_DIALOG_ZDMDESIGN            111
#define IDD_DIALOG_ZDMGEOFEATURES       112
#define IDD_DIALOG_ZDM_SLOPEDATA        113
#define IDD_DIALOG_ZDM_R                114
#define IDD_DIALOG_ZDM_STARTLC_H        115
#define IDD_DIALOG_ZDM_JTPCPD           116
#define IDD_DIALOG_TUNNEL               117
#define IDD_DIALOG_BRIDGE               118
#define IDD_DIALOG_GZWNAME              119
#define IDD_DIALOG_TUNNNELSET           120
#define IDD_DIALOG_BRIDGESET            121
#define IDD_DIALOG_TEXTURE_BP           122
#define IDD_DIALOG_TEXTURE_LJ           123
#define IDD_DIALOG_TEXTURE_BRIDGEHPM    124
#define IDD_DIALOG_TEXTURE_TUNNELDM     125
#define IDD_DIALOG_TEXTURE_TUNNEL       126
#define IDD_DIALOG_MODEL_QD             127
#define IDR_MAINFRAME                   128
#define IDR_T3DSYSTYPE                  129
#define ID_INDICATOR_MESSAGE            129
#define IDD_DIALOG_AVIPARAMETER         130
#define IDR_TOOLBAR_ORTHO               131
#define IDD_DIALOG_RECORDPICTURESPEED   132
#define IDR_MENU_PLANE                  133
#define IDD_DIALOG_PLANEGRAPHIC         136
#define IDB_SNOW_LARGE                  139
#define IDB_SNOW_MIDDLE                 140
#define IDB_SNOW_SMALL                  141
#define IDB_SNOW_FLOOR                  142
#define IDR_TOOLBAR_PLANE               145
#define IDR_MENU_ZDM                    173
#define IDR_TOOLBAR_ZDM                 189
#define IDC_EDIT_PROJECTNAME            1000
#define IDC_BUTTON_OPEN                 1000
#define IDC_SYSTEM_NAME                 1001
#define IDC_SYSTEM_PASSWORD             1002
#define IDC_SYSTEM_SERVERNAME           1004
#define IDC_BUTTON_BROWSE               1005
#define IDC_LIST_FILES                  1006
#define IDC_EDIT_ID                     1006
#define IDC_EDIT_FG_HEIGHT              1007
#define IDC_EDIT_NAME                   1007
#define IDC_EDIT_FG_WIDTH               1008
#define IDC_PROGRESS                    1009
#define IDC_EDIT_T                      1009
#define IDC_EDIT_DEMFILE                1010
#define IDC_EDIT_L                      1010
#define IDC_COMBO_BLOCKSIZE             1012
#define IDC_BUTTON_SAVE                 1012
#define IDC_EDIT_BLOCKINFOR             1013
#define IDC_COMBO_SUBBLOCKSIZE          1014
#define IDC_BUTTON_COLOR                1014
#define IDC_EDIT_LENGTH                 1014
#define IDC_EDIT_SUBBLOCKINFOR          1015
#define IDC_BUTTON_SEPERATE             1016
#define IDC_LIST                        1019
#define IDC_BUTTON_DELETE               1020
#define IDC_EDIT_R                      1021
#define IDC_BUTTON_CHECK                1025
#define IDC_EDIT_SHIZXLENGTH            1027
#define IDC_EDIT_RANGER                 1027
#define IDC_EDIT_ARCHEIGHT              1027
#define IDC_EDIT_HPANGLE                1027
#define IDC_EDIT_TUNNELHEIGHT           1028
#define IDC_BUTTON_EXIT                 1029
#define IDC_EDIT_WALLHEIGHT             1029
#define IDC_EDIT_E                      1032
#define IDC_EDIT_LC                     1033
#define IDC_MSFLEXGRID                  1034
#define IDC_EDIT_PDDSC                  1035
#define IDC_EDIT_FILENAME               1038
#define IDC_STATIC_X                    1047
#define IDC_STATIC_Y                    1048
#define IDC_BUTTON_ADD                  1111
#define IDC_BUTTON_EDIT                 1113
#define IDC_SLIDER_FRAME                1146
#define IDC_EDIT_FRAME                  1147
#define IDC_SLIDER_MOVIE_WIDTH          1166
#define IDC_SLIDER_MOVIE_HEIGHT         1167
#define IDC_EDIT_MOVIE_WIDTH            1168
#define IDC_EDIT_MOVIE_HEIGHT           1169
#define IDC_BUTTON_OUTPUT               1246
#define IDC_COMBO_GRADE                 1303
#define IDC_COMBO_DRAUGHTSTYLE          1304
#define IDC_COMBO_LOCOMOTIVE            1305
#define IDC_COMBO_SCHEMENAME            1306
#define IDC_EDIT_MINRADIUS              1307
#define IDC_COMBO_DESIGNSPEED           1309
#define IDC_COMBO_ENGINEERINGCONDITION  1310
#define IDC_COMBO_TERRAINSTYLE          1311
#define IDC_EDIT_CRITERIONMINR          1312
#define IDC_COMBO_DFXEFFICIENTLENGTH    1313
#define IDC_COMBO_BSSTYLE               1314
#define IDC_EDIT_CRITERIONMINPC         1315
#define IDC_EDIT_CRITERIONMAXSLOPEPD    1316
#define IDC_EDIT_CRITERIONMAXSLOPEPDDSC 1317
#define IDC_EDIT_STARTLC                1319
#define IDC_EDIT_ENDLC                  1320
#define IDC_EDIT_L0                     1322
#define IDC_EDIT_MINl0                  1323
#define IDC_EDIT_ARCSEGMENTNUMBERS      1323
#define IDC_EDIT_HLSPACE                1323
#define IDC_EDIT_MINR                   1324
#define IDC_EDIT_HLHEIGHT               1324
#define IDC_COMBO_R                     1325
#define IDC_EDIT_QDSPACE                1325
#define IDC_STATIC1                     1327
#define IDC_EDIT_HLWIDTH                1330
#define IDC_EDIT_SETBRIDGEHEIGHT        1331
#define IDC_STATIC_BMP                  1337
#define IDC_COMBOL_WIDTH                1348
#define IDC_EDIT_SHUZXHEIGHT            1349
#define IDC_EDIT_GEOFEATURE             1389
#define IDC_STATIC_LCCORINFO            1390
#define IDC_EDIT_H                      1391
#define IDC_EDIT_PD                     1392
#define IDC_RADIO_PCPD                  1394
#define IDC_RADIO_ZHBG                  1395
#define IDC_EDIT_STARTH                 1397
#define IDC_EDIT_MINPC                  1398
#define IDC_EDIT_MAXSLOPEPDDSC          1399
#define IDC_EDIT_MAXSLOPEPD             1400
#define IDC_STATIC_FRAME                1426
#define IDC_SLIDER_RECORDPICTURE_SPEED  1427
#define IDC_EDIT_RECORDPICTURESPEED     1428
#define ID_MENU_DEM                     32771
#define ID_MENU_TEXTUREIMAGE            32772
#define ID_MENU_NEWPROJECT              32773
#define ID_MENU_OPENPROJECT             32774
#define ID_DRAWMODE_LINE                32775
#define ID_DRAWMODE_RENDER              32776
#define ID_DRAWMODE_TEXTURE             32777
#define ID_SELECT_SET                   32778
#define ID_SPACEQUERY_SET               32779
#define ID_QUERY_COORDINATE             32780
#define ID_QUERY_DISTENCE               32781
#define ID_MENU_STEREO                  32782
#define ID_MENU_PERSPECTIVE             32783
#define ID_MENU_PROJECTTIONORTHO        32784
#define ID_ORTHO_ZOOMIN                 32785
#define ID_ORTHO_ZOOMOUT                32786
#define ID_BUTTON32787                  32787
#define ID_ORTHO_ZOOMORIGIN             32788
#define ID_ORTHO_PAN                    32789
#define ID_ORTHO_ZOOWINDOW              32790
#define ID_MENU_LINESCHEME              32791
#define ID_MENU_LINEDESIGN              32792
#define ID_MENU_LINESAVESCHEME          32793
#define ID_MENU_PLANE_GRAPH             32794
#define ID_MENU_PLANE_EXIT              32795
#define ID_GRAPH_MOVE2                  32796
#define ID_ZOOMWINDOW                   32797
#define ID_ZOOMIN                       32798
#define ID_ZOOMOUT                      32799
#define ID_MENU_PLANE_FULLSCREEN        32800
#define ID_MENU_ZDMDESIGN               32801
#define ID_TOOL_SCHEME                  32802
#define ID_MENU_BUILD3DLINEMODLE        32803
#define ID_FLY_ROUTINSCHEMELINE         32804
#define ID_FLY_STOP                     32805
#define ID_MENU_TUNNELSET               32806
#define ID_MENU_BRIDGESET               32807
#define ID_MENU_TEXTUREBP               32808
#define ID_MENUITEM32809                32809
#define ID_MENU_TEXTURELJ               32810
#define ID_MENU_TEXTUREQLHPM            32811
#define ID_MENU_TEXTURETUNNEL           32812
#define ID_MENU_TEXTURETUNNEL_DM        32813
#define ID_PATH_MANUINPUT               32814
#define ID_PATH_SETUP                   32815
#define ID_FLYPATH_SAVE                 32816
#define ID_FLY_DISPALYPATH              32817
#define ID_FLY_PAUSE                    32818
#define ID_FLY_ONESTEP                  32819
#define ID_FLPPATH_INTERPOLATION        32820
#define ID_FLY_OPENPATH                 32821
#define ID_FLY_ONOFFPATH                32823
#define ID_FLY_STATICHEIGHT             32824
#define ID_FLY_ROUTINEHEIGHT            32825
#define ID_FLY_PLAYPAUSE                32826
#define ID_FLY_VIEW_ENLARGE             32827
#define ID_FLY_VIEW_SMALL               32828
#define ID_FLY_HEIGHT_UP                32829
#define ID_FLY_HEIGHT_DOWN              32830
#define ID_FLY_VIEW_UP                  32831
#define ID_FLY_VIEW_DOWN                32832
#define ID_FLY_SPEED_UP                 32833
#define ID_FLY_SPEED_DOWN               32834
#define ID_MENU_MODLEQD                 32835
#define ID_MENU_OUPTCAD3DLINEMODEL      32836
#define ID_AVI_PARAMETER                32837
#define ID_MENUITEM32838                32838
#define ID_AVI_START                    32839
#define ID_AVI_PAUSE                    32840
#define ID_AVI_END                      32842
#define ID_SAVEPICTURE_SPEED            32843
#define ID_SAVEPICTURE_CONTINUE         32844
#define ID_SAVEPICTURE_STOP             32845
#define ID_MENU_SAVESCREENTOBMP         32846
#define ID_GRAPH_MOVE1                  32847
#define ID_GRAPH_MOVE3                  32849
#define ID_ZOOMINOUTDYNAMIC             32850
#define ID_MENU_PLANE_FIRSTSCREEN       32851
#define ID_MENU_PLANE_PRESCREEN         32852
#define ID_MENU_PLANE_NEXTSCREEN        32853
#define ID_MENU_PLANE_OUTCAD            32854
#define ID_BUTTON32858                  32858
#define ID_BUTTON32861                  32861
#define ID_MENU_ZDM_EXIT                32989
#define ID_MENU_ZDM_SLOPEDATA           32997
#define ID_ZDM_BACKGRID                 33001
#define ID_ZDM_LMBZ                     33003
#define ID_ZDM_GEOFEATURE               33004
#define ID_ZDM_DESIGN_ADDPT             33005
#define ID_ZDM_MENU_SAVE                33008
#define ID_MENU_ZDM_JDLPPCPD            33009
#define ID_ZDM_PENSET                   33010
#define ID_ZDM_STARTLC_H                33011
#define ID_TOOL_ZDM_SCHEME              33012
#define ID_TOOL_ZDM_XSCALE              33014
#define ID_TOOL_ZDM_YSCALE              33015
#define ID_TOOL_ZDM_XSCALETEXT          33016
#define ID_TOOL_ZDM_YSCALETEXT          33017
#define ID_TOOL_ZDM_LC_HINFO            33018
#define ID_ZDM_TUNNEL                   33020
#define ID_ZDM_BRIDGE                   33021
#define ID_PROGRESS                     33022
#define ID_TOOL_ZDM_PROGRESS            33028
#define ID_MENU_STATIONDATAS            33050
#define ID_ZDM_GRAPHBRIDGE              33067
#define ID_ZDM_GRAPHTUNNEL              33068
#define ID_ZDM_GRAPHSTATION             33069
#define ID_INDICATOR_LOADRENDERDEM      61446
#define ID_INDICATOR_FPS                61447
#define ID_INDICATOR_TRINUMBER          61448
#define ID_INDICATOR_FSANGLE            61449
#define ID_INDICATOR_VIEWPOS            61450
#define ID_INDICATOR_PROGRESSBAR        61451

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32865
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           133
#endif
#endif
