/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package irdc.ex06_13;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int b01=0x7f020000;
        public static final int b02=0x7f020001;
        public static final int b03=0x7f020002;
        public static final int b04=0x7f020003;
        public static final int b05=0x7f020004;
        public static final int b06=0x7f020005;
        public static final int b07=0x7f020006;
        public static final int black=0x7f02000a;
        public static final int blue=0x7f02000b;
        public static final int icon=0x7f020007;
        public static final int pic_icon=0x7f020008;
        public static final int white=0x7f020009;
    }
    public static final class id {
        public static final int bgImage=0x7f05001a;
        public static final int bgName=0x7f05001b;
        public static final int layout1=0x7f050000;
        public static final int layout2=0x7f050019;
        public static final int myButton1=0x7f050017;
        public static final int myButton2=0x7f050018;
        public static final int mySet1=0x7f050009;
        public static final int mySet2=0x7f05000a;
        public static final int mySet3=0x7f05000b;
        public static final int mySet4=0x7f05000c;
        public static final int mySet5=0x7f05000d;
        public static final int mySet6=0x7f05000e;
        public static final int mySet7=0x7f05000f;
        public static final int myText=0x7f05001c;
        public static final int myTitle0=0x7f050001;
        public static final int myTitle1=0x7f050002;
        public static final int myTitle2=0x7f050003;
        public static final int myTitle3=0x7f050004;
        public static final int myTitle4=0x7f050005;
        public static final int myTitle5=0x7f050006;
        public static final int myTitle6=0x7f050007;
        public static final int myTitle7=0x7f050008;
        public static final int setButton1=0x7f050010;
        public static final int setButton2=0x7f050011;
        public static final int setButton3=0x7f050012;
        public static final int setButton4=0x7f050013;
        public static final int setButton5=0x7f050014;
        public static final int setButton6=0x7f050015;
        public static final int setButton7=0x7f050016;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int preview=0x7f030001;
        public static final int progress=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
        public static final int str_button1=0x7f04000c;
        public static final int str_button2=0x7f04000d;
        public static final int str_noset=0x7f04000a;
        public static final int str_progress=0x7f04000e;
        public static final int str_set=0x7f04000b;
        public static final int str_title0=0x7f040002;
        public static final int str_title1=0x7f040003;
        public static final int str_title2=0x7f040004;
        public static final int str_title3=0x7f040005;
        public static final int str_title4=0x7f040006;
        public static final int str_title5=0x7f040007;
        public static final int str_title6=0x7f040008;
        public static final int str_title7=0x7f040009;
    }
}
