/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package irdc.ex05_24;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int darkgray=0x7f020001;
        public static final int icon=0x7f020000;
        public static final int white=0x7f020002;
    }
    public static final class id {
        public static final int myText1=0x7f050000;
        public static final int myText2=0x7f050001;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int row_layout=0x7f030001;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
        public static final int str_list0=0x7f040002;
        public static final int str_list1=0x7f040003;
        public static final int str_list10=0x7f04000c;
        public static final int str_list11=0x7f04000d;
        public static final int str_list12=0x7f04000e;
        public static final int str_list13=0x7f04000f;
        public static final int str_list2=0x7f040004;
        public static final int str_list3=0x7f040005;
        public static final int str_list4=0x7f040006;
        public static final int str_list5=0x7f040007;
        public static final int str_list6=0x7f040008;
        public static final int str_list7=0x7f040009;
        public static final int str_list8=0x7f04000a;
        public static final int str_list9=0x7f04000b;
    }
}
