/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package irdc.EX04_05;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int myCheckBox1=0x7f050002;
        public static final int myCheckBox2=0x7f050003;
        public static final int myCheckBox3=0x7f050004;
        public static final int myTextView1=0x7f050005;
        public static final int myTitle=0x7f050001;
        public static final int widget28=0x7f050000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int str_checkbox1=0x7f040002;
        public static final int str_checkbox2=0x7f040003;
        public static final int str_checkbox3=0x7f040004;
        public static final int str_title=0x7f040001;
    }
}
