/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package irdc.EX04_03;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int myButton=0x7f050003;
        public static final int myEditText=0x7f050002;
        public static final int myTextView=0x7f050001;
        public static final int widget28=0x7f050000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int str_Button=0x7f040000;
        public static final int str_TextView=0x7f040002;
    }
}
