/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_blogjava_mobile_jni_LowerToUpper */

#ifndef _Included_net_blogjava_mobile_jni_LowerToUpper
#define _Included_net_blogjava_mobile_jni_LowerToUpper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_blogjava_mobile_jni_LowerToUpper
 * Method:    getLine
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_blogjava_mobile_jni_LowerToUpper_getLine
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
