/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package irdc.ex08_05;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int myGallery01=0x7f050001;
        public static final int myLinearLayout=0x7f050000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
    }
    public static final class styleable {
        /** Attributes that can be used with a Gallery.
           <p>Includes the following attributes:</p>
           <table border="2" width="85%" align="center" frame="hsides" rules="all" cellpadding="5">
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute<th>Summary</tr>
           <tr><th><code>{@link #Gallery_android_galleryItemBackground irdc.ex08_05:android_galleryItemBackground}</code><td></tr>
           </table>
           @see #Gallery_android_galleryItemBackground
         */
        public static final int[] Gallery = {
            0x0101004c
        };
        /**
          <p>This symbol is the offset where the {@link irdc.ex08_05.R.attr#android_galleryItemBackground}
          attribute's value can be found in the {@link #Gallery} array.
          @attr name android:android_galleryItemBackground
        */
        public static final int Gallery_android_galleryItemBackground = 0;
    };
}
