/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package irdc.ex09_07;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int blue=0x7f020005;
        public static final int darkgray=0x7f020003;
        public static final int icon=0x7f020000;
        public static final int mappin_blue=0x7f020001;
        public static final int mappin_red=0x7f020002;
        public static final int white=0x7f020004;
    }
    public static final class id {
        public static final int myButton1=0x7f050002;
        public static final int myButton2=0x7f050003;
        public static final int myButton3=0x7f050004;
        public static final int myEditText1=0x7f050001;
        public static final int myMapView1=0x7f050005;
        public static final int myTextView1=0x7f050000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
        public static final int str_button1=0x7f040005;
        public static final int str_button2=0x7f040006;
        public static final int str_button3=0x7f040007;
        public static final int str_default_address=0x7f040004;
        public static final int str_latitude=0x7f040003;
        public static final int str_longitude=0x7f040002;
        public static final int str_to=0x7f040008;
    }
}
