/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package irdc.ex07_10;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int before=0x7f020000;
        public static final int black=0x7f02000a;
        public static final int blue=0x7f02000c;
        public static final int dance=0x7f020001;
        public static final int darkgray=0x7f020009;
        public static final int icon=0x7f020002;
        public static final int next=0x7f020003;
        public static final int pause=0x7f020004;
        public static final int pause_2=0x7f020005;
        public static final int star=0x7f020006;
        public static final int stars=0x7f020007;
        public static final int stop=0x7f020008;
        public static final int white=0x7f02000b;
    }
    public static final class id {
        public static final int before=0x7f050003;
        public static final int myImageButton1=0x7f050001;
        public static final int myImageButton2=0x7f050005;
        public static final int myImageView1=0x7f050006;
        public static final int myTextView1=0x7f050000;
        public static final int next=0x7f050004;
        public static final int pause=0x7f050002;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
        public static final int str_button1=0x7f040002;
        public static final int str_button2=0x7f040003;
        public static final int str_finished=0x7f040006;
        public static final int str_pause=0x7f040005;
        public static final int str_start=0x7f040004;
        public static final int str_stopped=0x7f040007;
    }
}
