/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package irdc.ex05_06;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int myTextView1=0x7f050000;
        public static final int myTextView2=0x7f050001;
        public static final int myTextView3=0x7f050002;
        public static final int myTextView4=0x7f050003;
        public static final int myTogglebutton1=0x7f050004;
        public static final int myTogglebutton2=0x7f050005;
        public static final int myTogglebutton3=0x7f050006;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
        public static final int str_end=0x7f040006;
        public static final int str_ok=0x7f040005;
        public static final int str_text1=0x7f040002;
        public static final int str_text2=0x7f040003;
        public static final int str_text3=0x7f040004;
    }
}
