/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package irdc.EX05_04;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int blue=0x7f020003;
        public static final int darkgray=0x7f020001;
        public static final int icon=0x7f020000;
        public static final int white=0x7f020002;
    }
    public static final class id {
        public static final int myButton1=0x7f050005;
        public static final int myEditText1=0x7f050003;
        public static final int myEditText2=0x7f050004;
        public static final int myEditText3=0x7f050007;
        public static final int myEditText4=0x7f050008;
        public static final int myTextView1=0x7f050001;
        public static final int myTextView2=0x7f050002;
        public static final int myTextView3=0x7f050006;
        public static final int widget34=0x7f050000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int str_button=0x7f040001;
        public static final int str_cc=0x7f040004;
        public static final int str_message=0x7f040002;
        public static final int str_receive=0x7f040003;
        public static final int str_subject=0x7f040005;
    }
}
