/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package irdc.EX04_14;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int black=0x7f020002;
        public static final int blue=0x7f020008;
        public static final int cyan=0x7f02000b;
        public static final int darkgray=0x7f020001;
        public static final int gray=0x7f020009;
        public static final int green=0x7f020004;
        public static final int icon=0x7f020000;
        public static final int lightgray=0x7f020005;
        public static final int magenta=0x7f02000a;
        public static final int red=0x7f020003;
        public static final int white=0x7f020006;
        public static final int yellow=0x7f020007;
    }
    public static final class id {
        public static final int myAnalogClock=0x7f050001;
        public static final int myTextView=0x7f050002;
        public static final int widget27=0x7f050000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
    }
}
