/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package irdc.ex10_03;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int black=0x7f020001;
        public static final int icon=0x7f020000;
        public static final int white=0x7f020002;
    }
    public static final class id {
        public static final int AbsoluteLayout01=0x7f050001;
        public static final int Button01=0x7f050000;
        public static final int Button02=0x7f050009;
        public static final int DatePicker01=0x7f05000a;
        public static final int EditText01=0x7f05000b;
        public static final int TextView01=0x7f050002;
        public static final int TextView02=0x7f050003;
        public static final int TextView03=0x7f050004;
        public static final int TextView04=0x7f050005;
        public static final int TextView05=0x7f050006;
        public static final int TextView07=0x7f050007;
        public static final int TextView08=0x7f050008;
        public static final int TimePicker01=0x7f05000c;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int main_1=0x7f030001;
    }
    public static final class string {
        public static final int app_name=0x7f040002;
        public static final int strButton1=0x7f040000;
        public static final int strButton2=0x7f040001;
        public static final int strMessage1=0x7f040003;
        public static final int strMessage2=0x7f040004;
        public static final int strMessage3=0x7f040005;
        public static final int strMessage4=0x7f040006;
        public static final int strMessage5=0x7f040007;
        public static final int strMessage6=0x7f040008;
        public static final int strMessage7=0x7f040009;
        public static final int strMessage8=0x7f04000a;
    }
}
