/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package irdc.ex10_06;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int blue=0x7f020004;
        public static final int darkgray=0x7f020002;
        public static final int hipposmall=0x7f020000;
        public static final int icon=0x7f020001;
        public static final int white=0x7f020003;
    }
    public static final class id {
        public static final int myButton1=0x7f050007;
        public static final int myButton2=0x7f05000a;
        public static final int myCheckedTextView1=0x7f05000e;
        public static final int myEditText1=0x7f050001;
        public static final int myEditText2=0x7f050003;
        public static final int myEditText3=0x7f050005;
        public static final int myListView1=0x7f05000c;
        public static final int myMapView1=0x7f050009;
        public static final int myTextView1=0x7f05000d;
        public static final int myTextView2=0x7f050000;
        public static final int myTextView3=0x7f050002;
        public static final int myTextView4=0x7f050004;
        public static final int myTextView5=0x7f050006;
        public static final int myTextView6=0x7f05000b;
        public static final int myTextView7=0x7f050008;
    }
    public static final class layout {
        public static final int layout_add=0x7f030000;
        public static final int layout_draw=0x7f030001;
        public static final int layout_edit=0x7f030002;
        public static final int layout_list=0x7f030003;
        public static final int main=0x7f030004;
        public static final int simple_list_item_single_choice=0x7f030005;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
        public static final int str_button1=0x7f04000a;
        public static final int str_cal=0x7f040009;
        public static final int str_cancel=0x7f04000e;
        public static final int str_del_it=0x7f04000d;
        public static final int str_edit_it=0x7f04000c;
        public static final int str_label1=0x7f040005;
        public static final int str_label2=0x7f040006;
        public static final int str_label3=0x7f040007;
        public static final int str_label4=0x7f040008;
        public static final int str_manu1=0x7f040002;
        public static final int str_manu2=0x7f040003;
        public static final int str_manu3=0x7f040004;
        public static final int str_whattodo=0x7f04000b;
    }
}
