/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package irdc.ex10_01;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int black=0x7f020007;
        public static final int blue=0x7f020003;
        public static final int green=0x7f020001;
        public static final int icon=0x7f020000;
        public static final int orange=0x7f020005;
        public static final int pink=0x7f020002;
        public static final int white=0x7f020006;
        public static final int yellow=0x7f020004;
    }
    public static final class id {
        public static final int myLinearLayout1=0x7f050001;
        public static final int myText=0x7f050000;
    }
    public static final class layout {
        public static final int change_color=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
        public static final int str_blue=0x7f040004;
        public static final int str_exit=0x7f04000a;
        public static final int str_green=0x7f040006;
        public static final int str_ok=0x7f040009;
        public static final int str_orange=0x7f040007;
        public static final int str_pink=0x7f040005;
        public static final int str_title=0x7f040002;
        public static final int str_white=0x7f040003;
        public static final int str_yellow=0x7f040008;
    }
}
