/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package irdc.ex05_17;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int blue=0x7f020003;
        public static final int darkgray=0x7f020001;
        public static final int icon=0x7f020000;
        public static final int white=0x7f020002;
    }
    public static final class id {
        public static final int myCheckBox1=0x7f050001;
        public static final int myTextView1=0x7f050000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040001;
        public static final int hello=0x7f040000;
        public static final int str_checked=0x7f040002;
        public static final int str_start_wifi_done=0x7f040005;
        public static final int str_start_wifi_failed=0x7f040004;
        public static final int str_stop_wifi_done=0x7f040007;
        public static final int str_stop_wifi_failed=0x7f040006;
        public static final int str_uncheck=0x7f040003;
        public static final int str_wifi_disabled=0x7f04000a;
        public static final int str_wifi_disabling=0x7f040009;
        public static final int str_wifi_enabling=0x7f040008;
        public static final int str_wifi_unknow=0x7f04000b;
    }
}
