/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package irdc.ex04_25;

public final class R {
    public static final class anim {
        public static final int cycle_7=0x7f040000;
        public static final int shake=0x7f040001;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int blue=0x7f020003;
        public static final int darkgray=0x7f020001;
        public static final int icon=0x7f020000;
        public static final int white=0x7f020002;
    }
    public static final class id {
        public static final int myButton1=0x7f060005;
        public static final int myButton2=0x7f060006;
        public static final int myOption1=0x7f060002;
        public static final int myOption2=0x7f060003;
        public static final int myOption3=0x7f060004;
        public static final int myRadioGroup1=0x7f060001;
        public static final int myTextView1=0x7f060000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f050001;
        public static final int hello=0x7f050000;
        public static final int str_button1=0x7f050002;
        public static final int str_button2=0x7f050003;
        public static final int str_guess_correct=0x7f050008;
        public static final int str_guess_error=0x7f050009;
        public static final int str_radio_op1=0x7f050005;
        public static final int str_radio_op2=0x7f050006;
        public static final int str_radio_op3=0x7f050007;
        public static final int str_radio_question1=0x7f050004;
    }
}
