/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.iceskysl.iTracks;

public final class R {
    public static final class array {
        /**  Used in View/setting.java 
         */
        public static final int gps=0x7f040000;
        public static final int map=0x7f040001;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int back=0x7f020000;
        public static final int con_track=0x7f020001;
        public static final int delete=0x7f020002;
        public static final int exit=0x7f020003;
        public static final int helps=0x7f020004;
        public static final int icon=0x7f020005;
        public static final int new_track=0x7f020006;
        public static final int setting=0x7f020007;
    }
    public static final class id {
        public static final int created=0x7f060014;
        public static final int desc=0x7f060015;
        public static final int gps=0x7f06000b;
        public static final int mv=0x7f060007;
        public static final int name=0x7f060013;
        public static final int new_desc=0x7f060001;
        public static final int new_name=0x7f060000;
        public static final int new_submit=0x7f060002;
        public static final int pane=0x7f06000f;
        public static final int pann=0x7f06000e;
        public static final int pans=0x7f060011;
        public static final int panw=0x7f060010;
        public static final int row=0x7f060012;
        public static final int sat=0x7f060008;
        public static final int setting_gps=0x7f060004;
        public static final int setting_map_level=0x7f060005;
        public static final int setting_submit=0x7f060006;
        public static final int setting_tips=0x7f060003;
        public static final int streetview=0x7f06000a;
        public static final int traffic=0x7f060009;
        public static final int zin=0x7f06000c;
        public static final int zout=0x7f06000d;
    }
    public static final class layout {
        public static final int helps=0x7f030000;
        public static final int main=0x7f030001;
        public static final int new_track=0x7f030002;
        public static final int setting=0x7f030003;
        public static final int show_track=0x7f030004;
        public static final int track_row=0x7f030005;
    }
    public static final class string {
        public static final int app_name=0x7f050005;
        public static final int app_title=0x7f050006;
        public static final int author=0x7f050020;
        public static final int author_text=0x7f050003;
        public static final int helps_infos=0x7f05001f;
        public static final int helps_text=0x7f050002;
        public static final int menu_back=0x7f05000d;
        public static final int menu_con=0x7f050009;
        public static final int menu_del=0x7f05000a;
        public static final int menu_exit=0x7f05000e;
        public static final int menu_helps=0x7f05000c;
        public static final int menu_main=0x7f050007;
        public static final int menu_new=0x7f050008;
        public static final int menu_setting=0x7f05000b;
        public static final int new_desc=0x7f050011;
        public static final int new_fail=0x7f050014;
        public static final int new_name=0x7f050010;
        public static final int new_name_null=0x7f050013;
        public static final int new_submit=0x7f050012;
        /** 新建跟踪界面
         */
        public static final int new_tips=0x7f05000f;
        /**  地图展示 
         */
        public static final int satellite=0x7f050021;
        public static final int setting_fail=0x7f05001a;
        public static final int setting_gps=0x7f050016;
        public static final int setting_map_level=0x7f050017;
        public static final int setting_null=0x7f050019;
        public static final int setting_ok=0x7f05001b;
        public static final int setting_submit=0x7f050018;
        /** 个人设置界面
         */
        public static final int setting_tips=0x7f050015;
        public static final int spinner_gps_prompt=0x7f05001c;
        public static final int spinner_map_prompt=0x7f05001d;
        public static final int start=0x7f050000;
        public static final int street=0x7f050023;
        public static final int title=0x7f050004;
        public static final int traffic=0x7f050022;
        /** 帮助信息界面
         */
        public static final int version=0x7f05001e;
        public static final int version_text=0x7f050001;
    }
}
