/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yarin_android_HelloNDK_Jni */

#ifndef _Included_com_yarin_android_HelloNDK_Jni
#define _Included_com_yarin_android_HelloNDK_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yarin_android_HelloNDK_Jni
 * Method:    getCInt
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jint JNICALL Java_com_yarin_android_HelloNDK_Jni_getCInt
  (JNIEnv *env, jobject thiz);

/*
 * Class:     com_yarin_android_HelloNDK_Jni
 * Method:    getCString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yarin_android_HelloNDK_Jni_getCString
  (JNIEnv *env, jobject thiz);

#ifdef __cplusplus
}
#endif
#endif
